### ISSUE TITLE
RCM

### ISSUE THREAD

**Issue by SeeThruHead** [beloglazov/arch-xmonad-zsh#1]
Hello! I just wanted to let you know of a utility called RCM that would allow you to combine your repos back into one, and install dotfiles based on tags or hostnames.

https://robots.thoughtbot.com/rcm-for-rc-files-in-dotfiles-repos

**Comment by beloglazov** [comment]
Thanks! That's a very nice tool. I actually went ahead and reorganized my configs using rcm into a new repo: https://github.com/beloglazov/dotfiles 

I like how you can select only the pieces you need using rcm's tags!
